// Generated by blog/04_samples/generate_performance_penalty_variants.py
const PERFORMANCE_PENALTY_VARIANTS = [
  {
    "id": "abcd",
    "order": [
      "a",
      "b",
      "c",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint8_t a;\n    uint8_t b;\n    uint8_t c;\n    uint8_t d;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t8b 07                \tmov    (%rdi),%eax\n   2:\tc3                   \tret",
    "instruction_count": 2
  },
  {
    "id": "dcba",
    "order": [
      "d",
      "c",
      "b",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint8_t c;\n    uint8_t b;\n    uint8_t a;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t8b 07                \tmov    (%rdi),%eax\n   2:\t0f c8                \tbswap  %eax\n   4:\tc3                   \tret",
    "instruction_count": 3
  },
  {
    "id": "adcb",
    "order": [
      "a",
      "d",
      "c",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t a;\n    uint8_t d;\n    uint8_t c;\n    uint8_t b;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t8b 07                \tmov    (%rdi),%eax\n   2:\t0f c8                \tbswap  %eax\n   4:\tc1 c0 08             \trol    $0x8,%eax\n   7:\tc3                   \tret",
    "instruction_count": 4
  },
  {
    "id": "badc",
    "order": [
      "b",
      "a",
      "d",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t b;\n    uint8_t a;\n    uint8_t d;\n    uint8_t c;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t8b 07                \tmov    (%rdi),%eax\n   2:\t0f c8                \tbswap  %eax\n   4:\tc1 c0 10             \trol    $0x10,%eax\n   7:\tc3                   \tret",
    "instruction_count": 4
  },
  {
    "id": "cbad",
    "order": [
      "c",
      "b",
      "a",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint8_t c;\n    uint8_t b;\n    uint8_t a;\n    uint8_t d;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t8b 07                \tmov    (%rdi),%eax\n   2:\t0f c8                \tbswap  %eax\n   4:\tc1 c8 08             \tror    $0x8,%eax\n   7:\tc3                   \tret",
    "instruction_count": 4
  },
  {
    "id": "abdc",
    "order": [
      "a",
      "b",
      "d",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t a;\n    uint8_t b;\n    uint8_t d;\n    uint8_t c;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 01          \tmovzbl 0x1(%rdi),%eax\n   4:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 17             \tmovzbl (%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "acbd",
    "order": [
      "a",
      "c",
      "b",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint8_t a;\n    uint8_t c;\n    uint8_t b;\n    uint8_t d;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 02          \tmovzbl 0x2(%rdi),%eax\n   4:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 17             \tmovzbl (%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "acdb",
    "order": [
      "a",
      "c",
      "d",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t a;\n    uint8_t c;\n    uint8_t d;\n    uint8_t b;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 03          \tmovzbl 0x3(%rdi),%eax\n   4:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 17             \tmovzbl (%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "adbc",
    "order": [
      "a",
      "d",
      "b",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t a;\n    uint8_t d;\n    uint8_t b;\n    uint8_t c;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 02          \tmovzbl 0x2(%rdi),%eax\n   4:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 17             \tmovzbl (%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "bacd",
    "order": [
      "b",
      "a",
      "c",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint8_t b;\n    uint8_t a;\n    uint8_t c;\n    uint8_t d;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 07             \tmovzbl (%rdi),%eax\n   3:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "bcad",
    "order": [
      "b",
      "c",
      "a",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint8_t b;\n    uint8_t c;\n    uint8_t a;\n    uint8_t d;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 07             \tmovzbl (%rdi),%eax\n   3:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "bcda",
    "order": [
      "b",
      "c",
      "d",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t b;\n    uint8_t c;\n    uint8_t d;\n    uint8_t a;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 07             \tmovzbl (%rdi),%eax\n   3:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "bdac",
    "order": [
      "b",
      "d",
      "a",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t b;\n    uint8_t d;\n    uint8_t a;\n    uint8_t c;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 07             \tmovzbl (%rdi),%eax\n   3:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "bdca",
    "order": [
      "b",
      "d",
      "c",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t b;\n    uint8_t d;\n    uint8_t c;\n    uint8_t a;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 07             \tmovzbl (%rdi),%eax\n   3:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "cabd",
    "order": [
      "c",
      "a",
      "b",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint8_t c;\n    uint8_t a;\n    uint8_t b;\n    uint8_t d;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 02          \tmovzbl 0x2(%rdi),%eax\n   4:\t0f b6 17             \tmovzbl (%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "cadb",
    "order": [
      "c",
      "a",
      "d",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t c;\n    uint8_t a;\n    uint8_t d;\n    uint8_t b;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 03          \tmovzbl 0x3(%rdi),%eax\n   4:\t0f b6 17             \tmovzbl (%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "cbda",
    "order": [
      "c",
      "b",
      "d",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t c;\n    uint8_t b;\n    uint8_t d;\n    uint8_t a;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 01          \tmovzbl 0x1(%rdi),%eax\n   4:\t0f b6 17             \tmovzbl (%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "cdab",
    "order": [
      "c",
      "d",
      "a",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t c;\n    uint8_t d;\n    uint8_t a;\n    uint8_t b;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 03          \tmovzbl 0x3(%rdi),%eax\n   4:\t0f b6 17             \tmovzbl (%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "cdba",
    "order": [
      "c",
      "d",
      "b",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t c;\n    uint8_t d;\n    uint8_t b;\n    uint8_t a;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 02          \tmovzbl 0x2(%rdi),%eax\n   4:\t0f b6 17             \tmovzbl (%rdi),%edx\n   7:\tc1 e0 08             \tshl    $0x8,%eax\n   a:\tc1 e2 10             \tshl    $0x10,%edx\n   d:\t09 d0                \tor     %edx,%eax\n   f:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  13:\t09 d0                \tor     %edx,%eax\n  15:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "dabc",
    "order": [
      "d",
      "a",
      "b",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint8_t a;\n    uint8_t b;\n    uint8_t c;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 02          \tmovzbl 0x2(%rdi),%eax\n   4:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  14:\t09 d0                \tor     %edx,%eax\n  16:\t0f b6 17             \tmovzbl (%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "dacb",
    "order": [
      "d",
      "a",
      "c",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint8_t a;\n    uint8_t c;\n    uint8_t b;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 03          \tmovzbl 0x3(%rdi),%eax\n   4:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n  14:\t09 d0                \tor     %edx,%eax\n  16:\t0f b6 17             \tmovzbl (%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "dbac",
    "order": [
      "d",
      "b",
      "a",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint8_t b;\n    uint8_t a;\n    uint8_t c;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 01          \tmovzbl 0x1(%rdi),%eax\n   4:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  14:\t09 d0                \tor     %edx,%eax\n  16:\t0f b6 17             \tmovzbl (%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "dbca",
    "order": [
      "d",
      "b",
      "c",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint8_t b;\n    uint8_t c;\n    uint8_t a;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 01          \tmovzbl 0x1(%rdi),%eax\n   4:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 57 03          \tmovzbl 0x3(%rdi),%edx\n  14:\t09 d0                \tor     %edx,%eax\n  16:\t0f b6 17             \tmovzbl (%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  },
  {
    "id": "dcab",
    "order": [
      "d",
      "c",
      "a",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint8_t c;\n    uint8_t a;\n    uint8_t b;\n} struct_example_t;",
    "asm_text": "0000000000000000 <foo>:\n   0:\t0f b6 47 03          \tmovzbl 0x3(%rdi),%eax\n   4:\t0f b6 57 01          \tmovzbl 0x1(%rdi),%edx\n   8:\tc1 e0 08             \tshl    $0x8,%eax\n   b:\tc1 e2 10             \tshl    $0x10,%edx\n   e:\t09 d0                \tor     %edx,%eax\n  10:\t0f b6 57 02          \tmovzbl 0x2(%rdi),%edx\n  14:\t09 d0                \tor     %edx,%eax\n  16:\t0f b6 17             \tmovzbl (%rdi),%edx\n  19:\tc1 e2 18             \tshl    $0x18,%edx\n  1c:\t09 d0                \tor     %edx,%eax\n  1e:\tc3                   \tret",
    "instruction_count": 11
  }
];
