// Generated by blog/04_samples/generate_struct_intro_variants.py
const STRUCT_INTRO_VARIANTS = [
  {
    "id": "abcd",
    "order": [
      "a",
      "b",
      "c",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint64_t a;\n    uint32_t b;\n    uint16_t c;\n    uint8_t d;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint64_t a; /* offset: 0, size: 8 */\n    uint32_t b; /* offset: 8, size: 4 */\n    uint16_t c; /* offset: 12, size: 2 */\n    uint8_t d; /* offset: 14, size: 1 */\n    /* size: 16, cachelines: 1, members: 4 */\n    /* padding: 1 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "abdc",
    "order": [
      "a",
      "b",
      "d",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint64_t a;\n    uint32_t b;\n    uint8_t d;\n    uint16_t c;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint64_t a; /* offset: 0, size: 8 */\n    uint32_t b; /* offset: 8, size: 4 */\n    uint8_t d; /* offset: 12, size: 1 */\n    /* padding: 1 */\n    uint16_t c; /* offset: 14, size: 2 */\n    /* size: 16, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "acdb",
    "order": [
      "a",
      "c",
      "d",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint64_t a;\n    uint16_t c;\n    uint8_t d;\n    uint32_t b;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint64_t a; /* offset: 0, size: 8 */\n    uint16_t c; /* offset: 8, size: 2 */\n    uint8_t d; /* offset: 10, size: 1 */\n    /* padding: 1 */\n    uint32_t b; /* offset: 12, size: 4 */\n    /* size: 16, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "adcb",
    "order": [
      "a",
      "d",
      "c",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint64_t a;\n    uint8_t d;\n    uint16_t c;\n    uint32_t b;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint64_t a; /* offset: 0, size: 8 */\n    uint8_t d; /* offset: 8, size: 1 */\n    /* padding: 1 */\n    uint16_t c; /* offset: 10, size: 2 */\n    uint32_t b; /* offset: 12, size: 4 */\n    /* size: 16, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "bcda",
    "order": [
      "b",
      "c",
      "d",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint32_t b;\n    uint16_t c;\n    uint8_t d;\n    uint64_t a;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint32_t b; /* offset: 0, size: 4 */\n    uint16_t c; /* offset: 4, size: 2 */\n    uint8_t d; /* offset: 6, size: 1 */\n    /* padding: 1 */\n    uint64_t a; /* offset: 8, size: 8 */\n    /* size: 16, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "bdca",
    "order": [
      "b",
      "d",
      "c",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint32_t b;\n    uint8_t d;\n    uint16_t c;\n    uint64_t a;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint32_t b; /* offset: 0, size: 4 */\n    uint8_t d; /* offset: 4, size: 1 */\n    /* padding: 1 */\n    uint16_t c; /* offset: 6, size: 2 */\n    uint64_t a; /* offset: 8, size: 8 */\n    /* size: 16, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "cdba",
    "order": [
      "c",
      "d",
      "b",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint16_t c;\n    uint8_t d;\n    uint32_t b;\n    uint64_t a;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint16_t c; /* offset: 0, size: 2 */\n    uint8_t d; /* offset: 2, size: 1 */\n    /* padding: 1 */\n    uint32_t b; /* offset: 4, size: 4 */\n    uint64_t a; /* offset: 8, size: 8 */\n    /* size: 16, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "dcba",
    "order": [
      "d",
      "c",
      "b",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint16_t c;\n    uint32_t b;\n    uint64_t a;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint8_t d; /* offset: 0, size: 1 */\n    /* padding: 1 */\n    uint16_t c; /* offset: 2, size: 2 */\n    uint32_t b; /* offset: 4, size: 4 */\n    uint64_t a; /* offset: 8, size: 8 */\n    /* size: 16, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 16,
    "total_holes": 1
  },
  {
    "id": "acbd",
    "order": [
      "a",
      "c",
      "b",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint64_t a;\n    uint16_t c;\n    uint32_t b;\n    uint8_t d;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint64_t a; /* offset: 0, size: 8 */\n    uint16_t c; /* offset: 8, size: 2 */\n    /* padding: 2 */\n    uint32_t b; /* offset: 12, size: 4 */\n    uint8_t d; /* offset: 16, size: 1 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 7 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "adbc",
    "order": [
      "a",
      "d",
      "b",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint64_t a;\n    uint8_t d;\n    uint32_t b;\n    uint16_t c;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint64_t a; /* offset: 0, size: 8 */\n    uint8_t d; /* offset: 8, size: 1 */\n    /* padding: 3 */\n    uint32_t b; /* offset: 12, size: 4 */\n    uint16_t c; /* offset: 16, size: 2 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 6 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "bacd",
    "order": [
      "b",
      "a",
      "c",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint32_t b;\n    uint64_t a;\n    uint16_t c;\n    uint8_t d;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint32_t b; /* offset: 0, size: 4 */\n    /* padding: 4 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint16_t c; /* offset: 16, size: 2 */\n    uint8_t d; /* offset: 18, size: 1 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 5 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "badc",
    "order": [
      "b",
      "a",
      "d",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint32_t b;\n    uint64_t a;\n    uint8_t d;\n    uint16_t c;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint32_t b; /* offset: 0, size: 4 */\n    /* padding: 4 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint8_t d; /* offset: 16, size: 1 */\n    /* padding: 1 */\n    uint16_t c; /* offset: 18, size: 2 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 4 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "bcad",
    "order": [
      "b",
      "c",
      "a",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint32_t b;\n    uint16_t c;\n    uint64_t a;\n    uint8_t d;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint32_t b; /* offset: 0, size: 4 */\n    uint16_t c; /* offset: 4, size: 2 */\n    /* padding: 2 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint8_t d; /* offset: 16, size: 1 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 7 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "bdac",
    "order": [
      "b",
      "d",
      "a",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint32_t b;\n    uint8_t d;\n    uint64_t a;\n    uint16_t c;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint32_t b; /* offset: 0, size: 4 */\n    uint8_t d; /* offset: 4, size: 1 */\n    /* padding: 3 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint16_t c; /* offset: 16, size: 2 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 6 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "cabd",
    "order": [
      "c",
      "a",
      "b",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint16_t c;\n    uint64_t a;\n    uint32_t b;\n    uint8_t d;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint16_t c; /* offset: 0, size: 2 */\n    /* padding: 6 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint32_t b; /* offset: 16, size: 4 */\n    uint8_t d; /* offset: 20, size: 1 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 3 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "cadb",
    "order": [
      "c",
      "a",
      "d",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint16_t c;\n    uint64_t a;\n    uint8_t d;\n    uint32_t b;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint16_t c; /* offset: 0, size: 2 */\n    /* padding: 6 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint8_t d; /* offset: 16, size: 1 */\n    /* padding: 3 */\n    uint32_t b; /* offset: 20, size: 4 */\n    /* size: 24, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "cbad",
    "order": [
      "c",
      "b",
      "a",
      "d"
    ],
    "struct_text": "typedef struct {\n    uint16_t c;\n    uint32_t b;\n    uint64_t a;\n    uint8_t d;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint16_t c; /* offset: 0, size: 2 */\n    /* padding: 2 */\n    uint32_t b; /* offset: 4, size: 4 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint8_t d; /* offset: 16, size: 1 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 7 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "cbda",
    "order": [
      "c",
      "b",
      "d",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint16_t c;\n    uint32_t b;\n    uint8_t d;\n    uint64_t a;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint16_t c; /* offset: 0, size: 2 */\n    /* padding: 2 */\n    uint32_t b; /* offset: 4, size: 4 */\n    uint8_t d; /* offset: 8, size: 1 */\n    /* padding: 7 */\n    uint64_t a; /* offset: 16, size: 8 */\n    /* size: 24, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "cdab",
    "order": [
      "c",
      "d",
      "a",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint16_t c;\n    uint8_t d;\n    uint64_t a;\n    uint32_t b;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint16_t c; /* offset: 0, size: 2 */\n    uint8_t d; /* offset: 2, size: 1 */\n    /* padding: 5 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint32_t b; /* offset: 16, size: 4 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 4 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "dabc",
    "order": [
      "d",
      "a",
      "b",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint64_t a;\n    uint32_t b;\n    uint16_t c;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint8_t d; /* offset: 0, size: 1 */\n    /* padding: 7 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint32_t b; /* offset: 16, size: 4 */\n    uint16_t c; /* offset: 20, size: 2 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 2 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "dacb",
    "order": [
      "d",
      "a",
      "c",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint64_t a;\n    uint16_t c;\n    uint32_t b;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint8_t d; /* offset: 0, size: 1 */\n    /* padding: 7 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint16_t c; /* offset: 16, size: 2 */\n    /* padding: 2 */\n    uint32_t b; /* offset: 20, size: 4 */\n    /* size: 24, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "dbac",
    "order": [
      "d",
      "b",
      "a",
      "c"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint32_t b;\n    uint64_t a;\n    uint16_t c;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint8_t d; /* offset: 0, size: 1 */\n    /* padding: 3 */\n    uint32_t b; /* offset: 4, size: 4 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint16_t c; /* offset: 16, size: 2 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 6 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "dbca",
    "order": [
      "d",
      "b",
      "c",
      "a"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint32_t b;\n    uint16_t c;\n    uint64_t a;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint8_t d; /* offset: 0, size: 1 */\n    /* padding: 3 */\n    uint32_t b; /* offset: 4, size: 4 */\n    uint16_t c; /* offset: 8, size: 2 */\n    /* padding: 6 */\n    uint64_t a; /* offset: 16, size: 8 */\n    /* size: 24, cachelines: 1, members: 4 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  },
  {
    "id": "dcab",
    "order": [
      "d",
      "c",
      "a",
      "b"
    ],
    "struct_text": "typedef struct {\n    uint8_t d;\n    uint16_t c;\n    uint64_t a;\n    uint32_t b;\n} foo_t;",
    "pahole_text": "typedef struct {\n    uint8_t d; /* offset: 0, size: 1 */\n    /* padding: 1 */\n    uint16_t c; /* offset: 2, size: 2 */\n    /* padding: 4 */\n    uint64_t a; /* offset: 8, size: 8 */\n    uint32_t b; /* offset: 16, size: 4 */\n    /* size: 24, cachelines: 1, members: 4 */\n    /* padding: 4 */\n} foo_t;",
    "total_size": 24,
    "total_holes": 9
  }
];
